[package]
name = "mvs_cli"
version = "0.5.0"
edition.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
keywords = ["mullvad", "socks5", "proxy", "filter", "cli"]

[[bin]]
name = "mvs_cli"
path = "mvs_cli.rs"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
mvs_lib = { path = "../mvs_lib" }
reqwest = { version = "0.12.9", default-features = false, features = [
    "blocking",
    "http2",
    "json",
    "rustls-tls",
] }
serde_json = "1.0.133"
