[package]
name = "mvs_lib"
version = "1.6.1"
edition.workspace = true
description.workspace = true
readme.workspace = true
keywords = ["mullvad", "socks5", "filter", "api", "json"]

[dependencies]
deunicode = "1.6.*"
serde = { version = "1.0.*", features = ["derive"] }

[dev-dependencies]
reqwest = { version = "0.12.*", default-features = false, features = [
    "blocking",
    "http2",
    "json",
    "rustls-tls",
] }

[lib]
name = "mvs_lib"
path = "mvs_lib.rs"
